# Generated by Django 5.1.5 on 2025-02-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_community_alter_forumthread_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='name',
            field=models.CharField(default='Default Community', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='forum_threads',
            field=models.ManyToManyField(blank=True, related_name='communities', to='myapp.forumthread'),
        ),
    ]
